name: libfmp_docs

dependencies:
  - python==3.10.*
  - pip
  - pip:
    - ipython>=8.10.0,<9.0.0
    - librosa>=0.10.0,<1.0.0
    - matplotlib>=3.3.0,<4.0.0
    - music21>=9.1.0,<10.0.0
    - numba>=0.58.1,<1.0.0
    - numpy>=1.19.0,<3.0.0
    - pandas>=1.1.0,<3.0.0
    - pretty_midi>=0.2.0,<1.0.0
    - soundfile>=0.9.0,<1.0.0
    - scipy>=1.5.0,<2.0.0
    # - libfmp  # using a freshly downloaded version of libfmp in the ci script
    - sphinx==7.4.*
    - sphinx_rtd_theme==2.0.*
