name: libfmp_docs

dependencies:
  - python==3.10.*
  - pip
  - pip:
    - ipython==8.38.*
    - librosa==0.10.*
    - matplotlib==3.3.*
    - music21==9.9.*
    - numba==0.59.*
    - pandas==2.3.*
    - pretty_midi==0.2.*
    - soundfile==0.9.*
    - scipy==1.5.*
    - numpy==1.26.*
    # - libfmp  # using a freshly downloaded version of libfmp in the ci script
    - sphinx==7.4.*
    - sphinx_rtd_theme==2.0.*
